version: "3.8"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    networks:
      - custom_network
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - database
    restart: always

  database:
    build: ./database
    ports:
      - "${PORT_DB}:${PORT_DB}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT_DB: ${PORT_DB}
    networks:
      - custom_network
    restart: always

networks:
  custom_network:
