version: '3.8'
services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
      - ./my_logs:/app/my_logs
    networks:
      - custom_network
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  database:
    build: ./database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT_DB: ${PORT_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - custom_network
    restart: always
    command:
      [
        'postgres',
        '-c',
        'logging_collector=on',
        '-c',
        'log_directory=./db_logs',
        '-c',
        'log_filename=postgresql.log',
        '-c',
        'log_statement=all',
      ]

networks:
  custom_network:
    driver: bridge
volumes:
  pgdata:
